### ISSUE TITLE
rawgit.org needs to renew it's SSL certs.

### ISSUE THREAD

**Issue by js-timbirkett** [alefnode/jenkins-themes#13]
Not sure who runs rawgit.org but its SSL cert has expired (not sure why they don't use Cloudflare's).

I got around the problem by moving to `jsdelivr`, example: https://cdn.jsdelivr.net/gh/alefnode/jenkins-themes@CDN/dist/material-red.css

**Comment by swiatlyk** [comment]
Hi,
same here. Most of the browsers can't use the link, and it's impossible to use the theme using url. As a workaround I open the theme .css in a new window, copy all the css file and put it to custom css rule.

**Comment by alefnode** [comment]
Ok, we can update URL, let's see that

**Comment by alefnode** [comment]
Seems that problem with rawgit is solved, i am think to add and alternate text to use when one fails

**Comment by alefnode** [comment]
As i said this MR https://github.com/alefnode/jenkins-themes/pull/22
