### ISSUE TITLE
The service is unavailable

### ISSUE THREAD

**Issue by thiagosanches** [alefnode/jenkins-themes#14]
Hi everyone, good morning.
I noticed today morning that the service is not avaiable:

```
curl -I https://jenkins-themes.alefnode.com/
HTTP/1.0 503 Service Unavailable
Cache-Control: no-cache
Connection: close
Content-Type: text/html
```

Thank you,
Regards.

**Comment by alefnode** [comment]
I am checking, my kubernetes cluster (small one, and managed myself) goes down when i tried to upgrade via kubespray

**Comment by alefnode** [comment]
Problem solved, web are up again

**Comment by thiagosanches** [comment]
Thanks @alefnode :)
