### ISSUE TITLE
New progress icons in Jenkins 2.289.1 display incorrectly

### ISSUE THREAD

**Issue by jjardina** [alefnode/jenkins-themes#15]
The new build in progress icon in Jenkins 2.289.1 display as previous icon, with new icon orbiting around it.  Very strange looking.  Is this a Jenkins issue or theme issue?

![buildinprogress](https://user-images.githubusercontent.com/40868102/120700753-07c2d880-c480-11eb-846b-40bcc9718994.PNG)

**Comment by offa** [comment]
Related: https://github.com/afonsof/jenkins-material-theme/issues/183

**Comment by offa** [comment]
**Workaround** ([source](https://github.com/afonsof/jenkins-material-theme/issues/183#issuecomment-806518351)):

Add an additional theme setting in the Jenkins theme settings:

```css
svg[class*=anime] { visibility: collapse }
```

**Comment by jjardina** [comment]
I implemented the work-around above and it has fixed the issue.  Thanks for the quick feedback!
