### ISSUE TITLE
Icon issue in version 2.289.1

### ISSUE THREAD

**Issue by olegsa** [alefnode/jenkins-themes#17]
After updating to Jenkins 2.289.1 there is an issue with the "running icon"
<br /><br /><br />
![](https://media.giphy.com/media/QLwsAHhjuvAsJ8Rb2U/giphy.gif)
![](https://media.giphy.com/media/ptPxtJnLbe39fIxgP4/giphy.gif)
![](https://media.giphy.com/media/oJk4JUUL3Vg4wxPkFt/giphy.gif)

**Comment by olegsa** [comment]
releated https://github.com/alefnode/jenkins-themes/issues/15

**Comment by alefnode** [comment]
Can you test it?

Should be fixed with that https://github.com/alefnode/jenkins-themes/pull/20

**Comment by alefnode** [comment]
Fixed now https://github.com/alefnode/jenkins-themes/commit/7a5834aad15e9ebf07625ef0a062cddb06055fcd

But i will update to adapt better in near future
