### ISSUE TITLE
Subpages doesn`t use the theme

### ISSUE THREAD

**Issue by sabf81** [alefnode/jenkins-themes#2]
I have generated a `jenkins-material-theme.css` file and add it as CSS-URL on my Jenkins.
On the sub(view)-pages this theme does not have any effect on it.

<img width="932" alt="no_theme_used" src="https://user-images.githubusercontent.com/13674691/84004783-69835c00-a96c-11ea-965e-d2f518897764.png">

**Comment by alefnode** [comment]
Are you using the correct url/path for css? it is working for me

![image](https://user-images.githubusercontent.com/19591155/84030140-cf370e80-a993-11ea-81ea-eef59e3f76e4.png)

**Comment by sabf81** [comment]
<img width="963" alt="jenkins_theme_url" src="https://user-images.githubusercontent.com/13674691/84110791-d575cb00-aa25-11ea-8ff8-278c5b3cde13.png">
Thats the path I have entered.
And thats the message I get in the java-script-console:
`Refused to apply style from 'https://ci.e-dict.net/jenkins/view/Deployment/view/Game-Deployment/userContent/layout/jenkins-material-theme.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`
If i open the url I get a 404 Message:

```
URI: | /jenkins/view/Deployment/view/Game-Deployment/userContent/layout/jenkins-material-theme.css
-- | --
404
Not Found
```

**Comment by alefnode** [comment]
It seems you are not using correct path or isn't upload in correct path, can you try using this url? https://jenkins-themes.alefnode.com/dist/material-blue.css

**Comment by sabf81** [comment]
Okay that works.
I have generated the single css file on your homepage, why is it not working?

**Comment by sabf81** [comment]
I got it. I have to change the css URL from
`userContent/layout/jenkins-material-theme.css `
to
`https://jenkins.url/jenkins/userContent/layout/jenkins-material-theme.css `
and now it works.
