### ISSUE TITLE
Is alefnode theme down?

### ISSUE THREAD

**Issue by thiagosanches** [alefnode/jenkins-themes#24]
Hey buddy, good morning.

I noticed that our Jenkins instance is not loading your CSS anymore.
I've tried to access the link and I got an error (403):

```
curl -I https://ghcdn.rawgit.org/alefnode/jenkins-themes/CDN/dist/material-red.css
HTTP/2 403 
content-type: text/html
date: Thu, 02 Jun 2022 14:51:37 GMT
server: NginX
vary: Accept-Encoding
content-length: 150
```

Thank you,
Regards.

**Comment by alefnode** [comment]
I am checking, i was upgrading my K8S cluster so i need a change in ContainerFile this MR should fix it https://github.com/alefnode/jenkins-themes/pull/25

**Comment by alefnode** [comment]
Alefnode is up an running again: https://jenkins-themes.alefnode.com/

Rawgit seems to be down, maybe you can use: https://raw.githubusercontent.com/alefnode/jenkins-themes/CDN/dist/material-red.css

or maybe: https://cdn.jsdelivr.net/gh/alefnode/jenkins-themes@CDN/dist/material-red.css
