### ISSUE TITLE
Pipeline logs issue

### ISSUE THREAD

**Issue by vinsguru** [alefnode/jenkins-themes#5]
Hi,
Thanks for these themes. They are awesome.
I just installed and everything looks great. However trying to view the logs from the pipeline view shows something like this.

![Screenshot from 2020-08-13 13-33-13](https://user-images.githubusercontent.com/6864530/90173204-b66b2080-dd69-11ea-8a04-42b2a2605bd8.png)

**Versions:**

![Screenshot from 2020-08-13 13-35-18](https://user-images.githubusercontent.com/6864530/90173297-dc90c080-dd69-11ea-9171-d649111bf8f0.png)

**Comment by alefnode** [comment]
Which browser are you using, i see correctly on my Firefox with this jenkins: 

https://jenkins.alefnode.com/job/public/job/slemos-imagebuilder-develop/

**Comment by vinsguru** [comment]
I used chrome.It works fine with your Jenkins url. Looks like it is completely 2 different theme versions. 
How to get the version you have?

![image](https://user-images.githubusercontent.com/6864530/91862551-bad17d80-ec33-11ea-8dd2-9856750271f7.png)

**Comment by alefnode** [comment]
I am using the url published directly

![image](https://user-images.githubusercontent.com/19591155/91944087-d30dcf00-ecfd-11ea-8d42-b61a3a32abb0.png)

**Comment by alefnode** [comment]
I modified some parts and now you can use Github CDN for css, can you test last code and tell me if bug continues?

Replace `{{your-color-name}}` in the URL by the chosen color: https://ghcdn.rawgit.org/alefnode/jenkins-themes/CDN/dist/material-{{your-color-name}}.css

**Comment by guillomep** [comment]
I have the problem too, in Firefox and Chrome.
I have used the Github CDN and I have a custom CSS for my logo.

**Comment by feurigel** [comment]
Hi,

that seems to be a Jenkins bug: https://issues.jenkins-ci.org/browse/JENKINS-63464
In the changelog you can see improvements for colors and background settings: https://www.jenkins.io/changelog/ (e.g. What's new in 2.240 (2020-06-08): Restore background colors on new item and job config pages.)

**Comment by feurigel** [comment]
Seems be fixed in Jenkins 2.249.1 (LTS).

**Comment by alefnode** [comment]
Perfect, we can close this issue
