### ISSUE TITLE
Issue with usage description on web page

### ISSUE THREAD

**Issue by CCFenner** [alefnode/jenkins-themes#6]
I guess changing the code to `<your-color-name>` should fix the issue.

https://github.com/alefnode/jenkins-themes#using-your-jenkins-hosting:

<img width="768" alt="Bildschirmfoto 2020-08-24 um 11 42 46" src="https://user-images.githubusercontent.com/26137398/91029440-0c0fba80-e5ff-11ea-8ed6-f49107d81599.png">

https://jenkins-themes.alefnode.com:

<img width="867" alt="Bildschirmfoto 2020-08-24 um 11 42 58" src="https://user-images.githubusercontent.com/26137398/91029452-0f0aab00-e5ff-11ea-9a36-c51426ac821e.png">

**Comment by alefnode** [comment]
Thanks for the advice, fixed here https://github.com/alefnode/jenkins-themes/pull/7
